services:
  db:
    image: postgres:16
    container_name: pack-trace-postgres
    environment:
      POSTGRES_USER: packtrace
      POSTGRES_PASSWORD: packtrace
      POSTGRES_DB: pack_trace
    ports:
      - "5432:5432"
    volumes:
      - pack-trace-postgres:/var/lib/postgresql/data

volumes:
  pack-trace-postgres:
